networks:
  graphql-net:
    driver: bridge

x-jdk-maven-common: &jdk_maven_common
  image: graphql-spring-boot
  working_dir: /usr/src/app
  volumes:
    - ./:/usr/src/app

services:
  server:
    <<: *jdk_maven_common
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    hostname: graphql
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - graphql-net
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005"
  unit_tests:
    <<: *jdk_maven_common
    networks:
      - graphql-net
    entrypoint: "./mvnw test"
